POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code REST Client is pretty good for testing REST APIs",
    "date": "2020-07-02T18:40:34.091Z",
    "important": false
}